sai-lab/rookie-training

vagrant/s12t270/Vagrantfile
Vagrantfileを編集し、ubuntu14.04の仮想マシンを起動した。
=> s12t270 #1 Vagrantfileの編集と起動

vagrant/s14g481/Vagrantfile
`vagrant up`するときは一斉にやらないこと:imp:
=> s14g481 #1 Vagrantfileの編集

vagrant/s12t230/Vagrantfile
=> s12t230  #1  Vagrantfile

vagrant/s12t252/Vagrantfile
ファイル名は大文字小文字を区別するので注意。
ファイル自体はrubyで書かれている。
vagrantコマンドは、up、ssh、status、halt、destroyによる操作を習った。
それぞれ起動、ログイン、ステータス確認、シャットダウン、完全削除である。
=> 12t252 #1 Vagrantfileの編集

vagrant/s15g485/Vagrantfile, vagrant/s15g485/apache.yml
Ansibleの概要学習と，設定ファイルであるyamlの書き方を学習した．
実際にapacheのインストールなどを実行させるyamlファイルを作成し，
前回作成したvagrantに対し実行した．
=> s15g485 #7 Ansible

vagrant/s12t230/Vagrantfile, vagrant/s12t230/apache.yml
・ ansibleの設定はymlファイルに記述
vagrant provision で読み込み
=> s12t230 #7 ansible

vagrant/s14g481/Vagrantfile, vagrant/s14g481/apache.yml
Ansibleを使い，Apacheパッケージのインストールとサービスの再起動を行った．
=> s14g481 #7 Ansibleを使ったApacheインストール

vagrant/s14g481/apache.yml, vagrant/s14g481/index.html.j2
Ansiblenのtemplateモジュールを使って，index.htmlを生成した．
=> s14g481 #12

vagrant/s15g485/apache.yml, vagrant/s15g485/index.html.j2
Ansibleのtemplateモジュールを用いてHTMLを生成する方法を学習した。
index.htmlを作成し、変数が展開されることを確認した。
=> s15g485 #12

vagrant/s12t252/Vagrantfile, vagrant/s12t252/index.html.j2
=> practice vagrant

vagrant/s12t270/apache.yml, vagrant/s12t270/index.html.j2
templateモジュールを使ってhtmlファイルを動的に生成した。
=> s12t270 ＃12

vagrant/s12t270/apache.yml, vagrant/s12t270/editor.yml, vagrant/s12t270/index.html.j2
includeを使ってplaybookを分割した。
playbook内で変数を宣言し、j2ファイルの中で使用できることを確認した。
=> s12t270 #18

vagrant/s14g481/apache.yml, vagrant/s14g481/editor.yml, vagrant/s14g481/index.html.j2
Emacsをインストールする`editor.yml`を作成し，`apache.yml`で`include`した．
`vars`では`my_name`を定義し，`index.html.j2`で展開した．
=> refs #18 Playbookの分割・変数

vagrant/s12t230/apache.yml, vagrant/s12t230/editor.yml, vagrant/s12t230/index.html.j2
=> #refs 18  変数と分割

vagrant/s15g485/apache.yml, vagrant/s15g485/editor.yml, vagrant/s15g485/index.html.j2
Emacsをインストールするeditor.ymlを作成し，apache.ymlでincludeした．
varsで変数を定義し，index.html.j2で展開できることを確認した．
=> refs #18 yml Playbookの分割・変数

vagrant/s13t264/Vagrantfile
=> refs #24 Vagrantfileの編集

vagrant/s13t208/Vagrantfile, vagrant/s13t208/apache.yml
**詰まった所**
- Ubuntuではhttpdではなく、apache2であることを知らなかった
=> refs #28 Ansibleを使ったApacheインストール

vagrant/s13t245/Vagrantfile, vagrant/s13t245/apache.yml
- 資料を見て行ったが、あっているか自信が持てず、詰まっていた。
- service を使った再起動において、state=relorded と state=restarted で迷った。state=restarted で実行。
- apt と service において、"name=" の後を "" で囲むのかで迷った。
=> refs 28 Ansibleを使ったApacheのインストール

vagrant/s13t264/apache.yml, vagrant/s13t264/index.html.j2
すぐできると考えていたが、j2ファイル内でansibleの変数が使えることが、わからず手間取ってしまった。
=> s13t264 #33

vagrant/s13t208/apache.yml, vagrant/s13t208/index.html.j2
最初は何をしていいか分からず厳しかった。
ansibleの実行が分かっていなかったため、変更を更新できずに苦労した。
=> s13t208 #33

vagrant/s13t245/apache.yml, vagrant/s13t245/index.html.j2
- 初めは index.html.j2 の書き方が一切わからず，止まっていた．
- 中でも変数の使い方がわからず，迷っていた．
=> refs #33 Ansibleのテンプレート機能

vagrant/s13t232/apache.yml, vagrant/s13t232/index.html.j2
Jinja2形式のテンプレートの書き方を把握するのに、少し時間がかかった。
また、Ansibleを再度走らせる際に vagrant provision を叩かないといけない
ことを理解しておらず、vagrant reload を叩いていた。
=> s13t232 #33

vagrant/s13t245/apache.yml, vagrant/s13t245/editor.yml, vagrant/s13t245/index.html.j2
- 初めはわからず、editor.yml の方にも hosts や sudo 等を記述していた
=> refs #40 Playbookの分割・変数

vagrant/s13t264/apache.yml, vagrant/s13t264/editor.yml
設定ファイルのコピーでcask関連で詰まったので止めた。
githubでスクリプト書いてるからいいかなって。
=> s13t264 #40

vagrant/s13t232/Vagrantfile, vagrant/s13t232/apache.rb
Rubyの記法が使えるので、Ansibleよりも書きやすく理解しやすかった。
=> refs #44 Itamaeを使ったApacheインストール

vagrant/s13t208/apache.yml, vagrant/s13t208/editor.yml, vagrant/s13t208/index.html.j2
=> ref #40 Playbookの分割・変数

vagrant/s13t245/Vagrantfile, vagrant/s13t245/apache.rb, vagrant/s13t245/templates/var/www/html/index.html.erb
- curl での表示で困ったが，`mode`オプションより，ファイルのパーミッションを 644 に変更することで解決．
- Ruby があまり書き慣れてないため，erb ファイルの記述や制御構文に少し苦労した．
=> refs #48 Itamaeのテンプレート機能

vagrant/s13t208/Vagrantfile, vagrant/s13t208/apache.rb
=> ref #44 Itamaeを使ったApacheインストール
